---

---


```{r, warning=FALSE, echo=FALSE, message=FALSE}
library(stringr)
library(dplyr)
library(tidyr)
library(tidytext)
library(ggplot2)
library(ggthemes)
library(gridExtra)
library(scales)
library(broom)
library(purrr)
library(topicmodels)
library(tm)
library(SnowballC) #stem

```


```{r}
#load the books
OARE_01 <- readLines("OARE_01.txt") %>%
  data_frame() %>%
  mutate(title = "OARE_01") 
```



```{r}
#regexp usage
fileName <- 'OARE_01.txt'
text <- readChar(fileName, file.info(fileName)$size)

res <- str_match(text, "Translation (.*?) AKT")
res[,2]

```

```{r}

# Replace line feeds with spaces
text <- gsub(pattern = "\\n", replacement = " ", x = text)

# Split string into words to find alternations of BOB / TRUDY
who <- strsplit(x = text, split = " ")[[1]]
who <- who[who %in% c("Translation")] 

# Split string using BOB: and TRUDY:
dialog <- strsplit(x = text, split = "(Translation)", perl = TRUE)[[1]][-1]

# create the two final vectors
bob <- trimws(dialog[which(who=="Translation")])
```

```{r}
fileName <- 'OARE_01.txt'
text <- readChar(fileName, file.info(fileName)$size)

gsub(".*Translation|\r \r.*", "", text)
```


```{r}
txt <- readLines("OARE_01.txt")
lns <- data.frame(beg=which(grepl("Translation",txt)),
                  end=which(grepl(regexpr("\n\n", txt, ignore.case = T),txt)))
txt.2 <- lapply(seq_along(lns$beg),function(l){
                         paste(txt[seq(from=lns$beg[l],
                                       to=lns$end[l],
                                       by=1)],collapse=" ")
                                       })
txt.2
```




```{r}
OARE_01 <- readLines("OARE_01.txt") %>%
  data_frame() %>%
  mutate(title = 'OARE_01')

colnames(OARE_01) <- c('text', 'title')

OARE_01 <- OARE_01[- grep("Translation", OARE_01$text),]
OARE_01 <- OARE_01[- grep("Epistolary Formula", OARE_01$text),]
OARE_01 <- OARE_01[- grep("logosyllabic, Akkadian", OARE_01$text),]
#OARE_01 <- OARE_01[- grep("Primary Classification: Text", OARE_01$text),]
s<-gsub("@.*","",rs)

OARE_01 <- OARE_01[gsub("Primary Classification: Text", "", OARE_01$text),]



```

```{r}
fileName <- 'OARE_01.txt'
text <- readChar(fileName, file.info(fileName)$size)

#text <- gsub(".*Translation", "", text)
#text <- gsub("Translation", "", text)

sapply(strsplit(text, "Translation"), "[", 2)

sub(".*?Translation(.*?)Translation.*", "\\1", text)
```
```{r}

txt <- readLines("OARE_01.txt") %>%
  data_frame() 

txt <- gsub('Translation','', txt)
txt <- gsub("Primary Classification:  Text",'', txt)
txt <- gsub("Epistolary Formula",'', txt)
txt <- gsub("Epistolary Form",'', txt)
txt <- gsub("logosyllabic, Akkadian",'', txt)

#gsub(str_detect(txt$., "Translation"), "", str_detect(txt$., "Translation")  

for(i in txt) {if (str_detect(i, "Translation") == T) {i = ''}}
for(i in txt) {if(i == 'Translation') {i == ''}}

```

```{r}
my_stop_words <- data.frame(word = c("Translation", "Primary Classification:  Text", 
                                        "Epistolary Formula",
                                         "Epistolary Form", "logosyllabic, Akkadian", "First Topic",
                                         "OARE Text-Document Type: Note", "OARE Text-Document Type: Note",
                                         "Physical Document Type: Tablet", "Topic"), 
                               lexicon = 'OARE')

#body <- "anti_join(txt, txt[grep('^Creator', txt$word),])"
#arg <- "Translation"

#eval(parse(text = paste('f <- function(', arg, txt,') { return(' , body , ')}', sep='')))
# Text it:
#f(3,2,5)

# Print text without standard stop words
#removeWords(text, stopwords("en"))
```







